version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
    ignore:
      - dependency-name: "prettier"
      - dependency-name: "prettier-plugin-astro"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
